### ISSUE TITLE
[Feature request] Include additional attributes in GET User?scope=full

### ISSUE THREAD

**Issue by urmade** [microsoft-campus-community/MCC-App_People-Engine#13]
**Is your feature request related to a problem? Please describe.**
In the MCC app frontend I need to check access to certain subpages. Internally, every user has a lead and admin boolean value, indicating if they have the access permissions of a lead or admin. When receiving users, I right now don't have any way to check what access level they are on.
Additionally, I would like to display the users position within MCC (Member, Lead, whatever may comes) but I don't have any way of getting this information.

**Describe the solution you'd like**
When calling GET /api/users?scope=full, I would like to get two boolean indicators: isLead and isAdmin. Also I would like you to include the position attribute that an Office user has. 

**Describe alternatives you've considered**
I could call MS Graph myself and check their access level or group memberships, but that would break the isolation and layered approach that we are currently implementing.

**Comment by felixSchober** [comment]
should be implemented in latest PR
