### ISSUE TITLE
[Bug] Get all campus returns empty array

### ISSUE THREAD

**Issue by urmade** [microsoft-campus-community/MCC-App_People-Engine#14]
**Describe the bug**
When calling, the API returns an empty array.

**To Reproduce**
1. Go to https://commasto-api-dev.azurewebsites.net/swagger/index.html.
2. Authorize.
3. Use the /api/hubs/campus GET request.

**Expected behavior**
I would expect to see a list of currently existing campus.

**Screenshots**
![image](https://user-images.githubusercontent.com/16389169/79382127-58693080-7f63-11ea-99b9-9bd3a06064f8.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS]
 - Browser [e.g. Microsoft Edge Anaheim]

**Additional context**

**Comment by felixSchober** [comment]
Done 

see #15
